# Generated by Django 5.2.8 on 2025-11-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KudosLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("from_email", models.EmailField(max_length=254)),
                ("to_email", models.EmailField(max_length=254)),
                ("reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "kudos_log",
                "indexes": [
                    models.Index(
                        fields=["to_email"], name="kudos_log_to_emai_6b51db_idx"
                    ),
                    models.Index(
                        fields=["from_email", "to_email", "timestamp"],
                        name="kudos_log_from_em_5c0028_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KudosView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_email", models.EmailField(max_length=254, unique=True)),
                ("total_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "kudos_view",
                "indexes": [
                    models.Index(
                        fields=["to_email"], name="kudos_view_to_emai_b121fc_idx"
                    )
                ],
            },
        ),
    ]
