"""
Django settings for peer_support_hub project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from app.services import initialize_gspread
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-z-o^ar0@@vn*(+lm+vr$f(409z&zmlh_#^vrd4bolpthc_d8$4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "peer_support_hub.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "peer_support_hub.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

GSPREAD_CLIENT = initialize_gspread()

# Allowed emails that can give kudos
ALLOWED_KUDOS_GIVERS = [
    # Add allowed email addresses here (lowercase)
    # Example: 'user@example.com',
    # 'another@example.com',
    'kmakki48@gmail.com',
    'gaisamuel34@gmail.com',
    'spizhov22y@gmail.com',
    'omniaagabani99@gmail.com',
    'chrismylp1@gmail.com',
    'dadi29skl@gmail.com',
    'hibayassir21@gmail.com',
    'alemayehu8363@gmail.com',
    'ireosama1@gmail.com',
    'hasan.zamzam@gmail.com',
    'raneem.ram06@gmail.com',
    'sh.shadab1988@gmail.com',
    'robmilthon24@gmail.com',
    'mnageeb153@gmail.com',
    'obey19955@gmail.com',
    'zaidmazenaltahhan@gmail.com',
    'elochukwuodoeze@gmail.com',
    'hodamalik622@gmail.com',
    'sskalender@gmail.com',
    'isaackibwe646@gmail.com',
    'ramon.colmenaresblanco@gmail.com',
    'bussiness.hn24@outlook.com',
    'rafaa202@outlook.com',
    'mohd.maky@gmail.com',
    'muhammadshahroz1019@gmail.com',
    'mohamedaltayeb2001@gmail.com',
    'abdulqaderdost@yahoo.com',
    'majdadelalsoud@gmail.com',
    'mervilpierrekenley07@gmail.com',
    'vahablotfi1@gmail.com',
    'maythant3807@gmail.com',
    'safiya.hash@gmail.com',
    'ava.abdullaah@gmail.com',
]